version: "3"

services:
  postgres:
    image: "postgres:11.4-alpine"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  sidekiq:
    build: .
    restart: always
    command: bundle exec sidekiq
    networks:
      - backend

  redis:
    image: redis:5.0.5-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.3.0
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backend

  app:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/my-app
    networks:
      - backend

volumes:
  postgres:
  redis:
  elasticsearch:

networks:
  backend:
    driver: "bridge"