version: "3"

services:
  postgres:
    image: "postgres:11.4-alpine"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  sidekiq:
    build: .
    restart: always
    command: bundle exec sidekiq
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/my-app
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    networks:
      - backend

  redis:
    image: redis:5.0.5-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
       - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - backend

  app:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
      - redis
    volumes:
      - .:/my-app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    networks:
      - backend

volumes:
  postgres:
  redis:
  elasticsearch_data:
    driver: local

networks:
  backend:
    driver: "bridge"